spring:
  application:
    name: order-service
    
#server:
#  port: 9201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
      
      
     
---
spring:
  profiles: order1
  
server:
  port: 9201
  
  
---
spring:
  profiles: order2

server:
  port: 9202            